# Generated by Django 3.2 on 2021-05-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundomodel',
            old_name='title',
            new_name='slug',
        ),
    ]
