# Generated by Django 3.2 on 2021-05-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0006_anunsiu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SgpStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
