# Generated by Django 3.2 on 2021-05-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0007_sgpstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgpstaff',
            name='staff',
            field=models.ImageField(blank=True, upload_to='staff'),
        ),
    ]
