# Generated by Django 3.2 on 2021-05-21 03:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0012_cafimembro_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorcesuPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('konteudu', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.AlterField(
            model_name='cafimembro',
            name='cargo',
            field=models.CharField(blank=True, choices=[('presidente', 'presidente'), ('membro', 'membro')], max_length=50),
        ),
    ]
