# Generated by Django 3.1.4 on 2021-05-21 07:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0013_auto_20210521_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudoViabialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('konteudu', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
