# Generated by Django 3.2 on 2021-05-21 12:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0014_estudoviabialidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliasaun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('konteudu', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
