# Generated by Django 3.2 on 2021-05-23 09:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0015_avaliasaun'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunsiu',
            name='konteudu_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='anunsiu',
            name='konteudu_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='anunsiu',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anunsiu',
            name='title_pt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
