# Generated by Django 3.2 on 2021-05-23 11:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0017_auto_20210523_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunsiu',
            name='konteudu_ind',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='anunsiu',
            name='title_ind',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='noticias',
            name='konteudu_ind',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='noticias',
            name='title_ind',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
