# Generated by Django 3.2 on 2021-05-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0019_auto_20210524_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='lian',
        ),
        migrations.AddField(
            model_name='sgpstaff',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sgpstaff',
            name='title_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sgpstaff',
            name='title_tt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
