# Generated by Django 3.2 on 2021-05-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0026_auto_20210525_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='data',
            field=models.DateField(),
        ),
    ]
