# Generated by Django 3.2 on 2021-05-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0027_alter_noticias_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunsiu',
            name='data',
            field=models.DateField(),
        ),
    ]
