# Generated by Django 3.1.4 on 2021-06-10 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0032_auto_20210602_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programas',
            name='slug_en',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='slug_pt',
        ),
        migrations.RemoveField(
            model_name='programas',
            name='slug_tt',
        ),
    ]
