# Generated by Django 3.1.4 on 2021-09-16 00:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0033_auto_20210610_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliasaun',
            name='konteudu_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='avaliasaun',
            name='konteudu_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='avaliasaun',
            name='konteudu_tt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='avaliasaun',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='avaliasaun',
            name='title_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='avaliasaun',
            name='title_tt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
