# Generated by Django 3.2 on 2021-05-17 10:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0002_rename_title_fundomodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SgpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('konteudu', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
