# Generated by Django 3.2 on 2021-05-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0004_noticias'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='lian',
            field=models.CharField(blank=True, choices=[('english', 'english'), ('portugues', 'portugues'), ('tetum', 'tetum')], max_length=20),
        ),
    ]
