# Generated by Django 3.2 on 2021-05-21 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0009_rename_staff_sgpstaff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgpstaff',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
