# Generated by Django 3.2 on 2021-05-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0018_auto_20210523_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anunsiu',
            old_name='konteudu_ind',
            new_name='konteudu_tt',
        ),
        migrations.RenameField(
            model_name='anunsiu',
            old_name='title_ind',
            new_name='title_tt',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='konteudu_ind',
            new_name='konteudu_tt',
        ),
        migrations.RenameField(
            model_name='noticias',
            old_name='title_ind',
            new_name='title_tt',
        ),
    ]
