# Generated by Django 3.2 on 2021-05-24 03:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0023_auto_20210524_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudoviabialidade',
            name='konteudu_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='estudoviabialidade',
            name='konteudu_pt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='estudoviabialidade',
            name='konteudu_tt',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='estudoviabialidade',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estudoviabialidade',
            name='title_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estudoviabialidade',
            name='title_tt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
