# Generated by Django 3.2 on 2021-05-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0024_auto_20210524_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafimembro',
            name='cargo_en',
            field=models.CharField(blank=True, choices=[('president', 'president'), ('member', 'member')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cafimembro',
            name='cargo_pt',
            field=models.CharField(blank=True, choices=[('presidente', 'presidente'), ('membro', 'membro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cafimembro',
            name='cargo_tt',
            field=models.CharField(blank=True, choices=[('presidente', 'presidente'), ('membru', 'membru')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cafimembro',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cafimembro',
            name='title_pt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cafimembro',
            name='title_tt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
