# Generated by Django 3.2 on 2021-05-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0025_auto_20210525_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafimembro',
            name='cargo',
            field=models.CharField(blank=True, choices=[('presidente', 'presidente'), ('membru', 'membru'), ('presidente', 'presidente'), ('membro', 'membro'), ('president', 'president'), ('member', 'member')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cafimembro',
            name='cargo_en',
            field=models.CharField(blank=True, choices=[('presidente', 'presidente'), ('membru', 'membru'), ('presidente', 'presidente'), ('membro', 'membro'), ('president', 'president'), ('member', 'member')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cafimembro',
            name='cargo_pt',
            field=models.CharField(blank=True, choices=[('presidente', 'presidente'), ('membru', 'membru'), ('presidente', 'presidente'), ('membro', 'membro'), ('president', 'president'), ('member', 'member')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cafimembro',
            name='cargo_tt',
            field=models.CharField(blank=True, choices=[('presidente', 'presidente'), ('membru', 'membru'), ('presidente', 'presidente'), ('membro', 'membro'), ('president', 'president'), ('member', 'member')], max_length=50, null=True),
        ),
    ]
