# Generated by Django 3.1.4 on 2021-06-02 08:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpsapps', '0028_alter_anunsiu_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('konteudu', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='programas')),
            ],
        ),
    ]
